### ISSUE TITLE
There's Bug that TAD Will Auto Claim if doing UNSTAKING the TEN Coin 

### ISSUE THREAD

**Issue by jeremycl99** [Tadpole-finance/TadGenesisMining#1]
There is bug in tadpole finance genesis mining. 

If we unstaking the TEN coin it will automatically claim the TAD coin and TAD coin automatically sent to our MetaMask wallet.

Although there is a button to claim TAD coin itself.

Thank you. i hopefully this help something.

**Comment by ngkong** [comment]
This is an intended behaviour to safe gas, thanks for reporting
